"""Create Word, Excel and PDF drafts from lawyer-approved structured content.

This is an output worker, not a general file editor.  It does not open or
overwrite source documents: the caller supplies an immutable approved content
snapshot and stores the resulting bytes in the encrypted managed artifact
area.  Formula execution, macros, external links and arbitrary file paths are
outside this worker's contract.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from hashlib import sha256
from html import escape as xml_escape
from io import BytesIO
from math import ceil, isfinite
from pathlib import Path
import re
import sys
from threading import Lock
from typing import Iterable
from unicodedata import category, east_asian_width
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo

from docx import Document
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Mm, Pt, RGBColor
from openpyxl import Workbook
from openpyxl.cell import WriteOnlyCell
from openpyxl.styles import Alignment, Border, Font, NamedStyle, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.properties import PageSetupProperties
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import Color
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas


class ApprovedDraftBlocked(ValueError):
    """A proposed document is not an approved bounded draft input."""


@dataclass(frozen=True)
class ApprovedSection:
    heading: str
    paragraphs: tuple[str, ...]
    source_refs: tuple[str, ...]


@dataclass(frozen=True)
class ApprovedDraft:
    title: str
    sections: tuple[ApprovedSection, ...]
    approval_hash: str


@dataclass(frozen=True)
class DraftArtifact:
    media_type: str
    content: bytes
    content_sha256: str


_MAX_SECTIONS = 200
_MAX_PARAGRAPHS = 20_000
_MAX_TEXT_CHARS = 1_000_000
_MAX_SHEETS = 100
_MAX_ROWS = 100_000
_MAX_COLUMNS = 200
_MAX_LEDGER_TEXT_CHARS = 10_000_000
_MAX_LEDGER_PRINT_LINES_PER_ROW = 20
_PDF_TEXT_FONT = "LawcaseEmbeddedSong"
_PDF_HEADING_FONT = "LawcaseEmbeddedHei"
_PDF_SECONDARY_FONT = "LawcaseEmbeddedKai"
_MANAGED_PDF_BODY_FONT = Path(
    "/usr/share/fonts/truetype/arphic/uming.ttc"
)
_MANAGED_PDF_HEADING_FONT = Path(
    "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc"
)
_MANAGED_PDF_SECONDARY_FONT = Path(
    "/usr/share/fonts/truetype/arphic/ukai.ttc"
)
_MACOS_PDF_BODY_FONT = Path("/System/Library/Fonts/Supplemental/Songti.ttc")
_MACOS_PDF_HEADING_FONT = Path("/System/Library/Fonts/STHeiti Medium.ttc")
_PDF_FONT_REGISTRATION_LOCK = Lock()
# Keep the editable OOXML identity stable across worker platforms.  Domestic
# Windows installations have these conventional families; macOS alternatives
# are declared in ``fontTable.xml``; managed Linux maps the same names to the
# pinned Noto CJK packages through the project fontconfig contract.  A DOCX
# generated by Linux must not become unreadable merely because a reviewing
# lawyer opens it on another operating system.
_DOCX_TITLE_FONT = "黑体"
_DOCX_HEADING_FONT = "黑体"
_DOCX_SECONDARY_HEADING_FONT = "楷体"
_DOCX_BODY_FONT = "宋体"
_DOCX_NOTE_FONT = "楷体"
_DOCX_FONT_ALTERNATES = {
    "黑体": "Heiti SC",
    "楷体": "Songti SC",
    "宋体": "Songti SC",
}
_XLSX_TITLE_FONT = "黑体"
_XLSX_HEADER_FONT = "黑体"
_XLSX_BODY_FONT = "宋体"
_CANDIDATE_STATUS = "律师复核候选｜待律师终审｜非正式文书"
_RECEIPT_TIME_NOTE = "生成时间以系统版本回执为准"
_SOURCE_NOTE_STYLE = "来源注记"
_REVIEW_NOTE_STYLE = "复核提示"
_OOXML_TIMESTAMP = (2000, 1, 1, 0, 0, 0)
_OOXML_CORE_DATETIME = datetime(2000, 1, 1, 0, 0, 0)
_OOXML_CORE_DATETIME_TEXT = b"2000-01-01T00:00:00Z"
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_UNSAFE_XML_TEXT_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\ud800-\udfff]")


def create_docx_draft(draft: ApprovedDraft) -> DraftArtifact:
    _validate_draft(draft)
    document = Document()
    _configure_domestic_docx(document)
    document.core_properties.title = draft.title
    document.core_properties.subject = "国内律师内部复核候选（非正式文书）"
    document.core_properties.category = "律师复核候选"
    document.core_properties.identifier = draft.approval_hash
    document.core_properties.author = "律所案件AI工作台"
    document.core_properties.last_modified_by = "律所案件AI工作台"
    # Office packages require core timestamps.  Use a stable packaging epoch;
    # the authoritative generation time remains the audited system receipt.
    document.core_properties.created = _OOXML_CORE_DATETIME
    document.core_properties.modified = _OOXML_CORE_DATETIME
    document.add_heading(draft.title, level=0)
    document.add_paragraph(
        f"{_CANDIDATE_STATUS}｜{_RECEIPT_TIME_NOTE}｜版本摘要 {draft.approval_hash[:12]}",
        style=_REVIEW_NOTE_STYLE,
    )
    for section in draft.sections:
        document.add_heading(section.heading, level=_heading_level(section.heading))
        for paragraph in section.paragraphs:
            document.add_paragraph(paragraph)
        document.add_paragraph(
            "来源注记：" + "；".join(section.source_refs),
            style=_SOURCE_NOTE_STYLE,
        )
    destination = BytesIO()
    document.save(destination)
    return _artifact(
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        _deterministic_ooxml(
            destination.getvalue(),
            docx_fonts=(
                _DOCX_TITLE_FONT,
                _DOCX_HEADING_FONT,
                _DOCX_SECONDARY_HEADING_FONT,
                _DOCX_BODY_FONT,
                _DOCX_NOTE_FONT,
            ),
        ),
    )


def create_xlsx_ledger(
    *,
    approval_hash: str,
    sheet_name: str,
    columns: tuple[str, ...],
    rows: Iterable[tuple[str | int | float | Decimal | date | datetime | None, ...]],
) -> DraftArtifact:
    _validate_approval_hash(approval_hash)
    if (
        not sheet_name.strip()
        or len(sheet_name) > 31
        or any(char in sheet_name for char in "[]:*?/\\")
        or _UNSAFE_XML_TEXT_RE.search(sheet_name)
    ):
        raise ApprovedDraftBlocked("ledger sheet name is invalid")
    if not 1 <= len(columns) <= _MAX_COLUMNS or any(
        not value.strip() or len(value) > 160 or _UNSAFE_XML_TEXT_RE.search(value)
        for value in columns
    ):
        raise ApprovedDraftBlocked("ledger columns are invalid")
    validated_rows: list[
        tuple[str | int | float | Decimal | date | datetime | None, ...]
    ] = []
    row_count = 0
    text_characters = sum(len(column) for column in columns)
    for row in rows:
        if len(row) != len(columns):
            raise ApprovedDraftBlocked("ledger row width does not match columns")
        values = tuple(_safe_cell_value(value) for value in row)
        text_characters += sum(len(value) for value in values if isinstance(value, str))
        if text_characters > _MAX_LEDGER_TEXT_CHARS:
            raise ApprovedDraftBlocked("ledger text exceeds the supported boundary")
        validated_rows.append(values)
        row_count += 1
        if row_count > _MAX_ROWS:
            raise ApprovedDraftBlocked("ledger row limit exceeded")
    if row_count == 0:
        raise ApprovedDraftBlocked("ledger requires at least one approved row")
    clean_sheet_name = sheet_name.strip()
    workbook = Workbook(write_only=True)
    _configure_domestic_workbook_metadata(workbook, clean_sheet_name, approval_hash)
    styles = _register_domestic_xlsx_styles(workbook)
    sheet = workbook.create_sheet(title=clean_sheet_name)
    _configure_domestic_ledger_sheet(
        sheet,
        columns=columns,
        rows=validated_rows,
        approval_hash=approval_hash,
    )
    last_column = get_column_letter(len(columns))
    if len(columns) > 1:
        sheet.merged_cells.add(f"A1:{last_column}1")
        sheet.merged_cells.add(f"A2:{last_column}2")
    sheet.append([_xlsx_cell(sheet, clean_sheet_name, styles["title"])])
    sheet.append([
        _xlsx_cell(
            sheet,
            f"{_CANDIDATE_STATUS}｜{_RECEIPT_TIME_NOTE}｜版本摘要 {approval_hash[:12]}",
            styles["notice"],
        )
    ])
    sheet.append([_xlsx_cell(sheet, value, styles["header"]) for value in columns])
    for row in validated_rows:
        sheet.append(
            [
                _xlsx_cell(sheet, value, _xlsx_data_style(styles, columns[index], value))
                for index, value in enumerate(row)
            ]
        )
    destination = BytesIO()
    workbook.save(destination)
    return _artifact(
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        _deterministic_ooxml(destination.getvalue()),
    )


def create_pdf_draft(draft: ApprovedDraft) -> DraftArtifact:
    _validate_draft(draft)
    _register_domestic_pdf_fonts()
    destination = BytesIO()
    document = canvas.Canvas(
        destination,
        pagesize=A4,
        pageCompression=1,
        invariant=1,
        # ReportLab otherwise creates an unused, unembedded Helvetica resource.
        initialFontName=_PDF_TEXT_FONT,
    )
    document.setTitle(draft.title)
    document.setAuthor("律所案件AI工作台")
    document.setCreator("律所案件AI工作台")
    document.setSubject("国内律师内部复核候选（非正式文书）")
    document.setKeywords(f"律师复核候选 candidate_sha256:{draft.approval_hash}")
    writer = _DomesticPdfWriter(document)
    width, height = A4
    content_width = width - writer.left_margin - writer.right_margin
    y = height - writer.top_margin
    document.setFillColorRGB(0, 0, 0)
    for title_line in _wrap(
        draft.title,
        content_width,
        18,
        font_name=_PDF_HEADING_FONT,
    ):
        y = writer.ensure_y(y, minimum=writer.bottom_margin + 22)
        _draw_pdf_text(document, writer.left_margin + content_width / 2, y, title_line, 18, centered=True, bold=True)
        y -= 24
    document.setFillColor(Color(0.32, 0.32, 0.32))
    review_line = f"{_CANDIDATE_STATUS}｜{_RECEIPT_TIME_NOTE}｜版本摘要 {draft.approval_hash[:12]}"
    for line in _wrap(
        review_line,
        content_width,
        10,
        font_name=_PDF_SECONDARY_FONT,
    ):
        y = writer.ensure_y(y, minimum=writer.bottom_margin + 18)
        _draw_pdf_text(
            document,
            writer.left_margin + content_width / 2,
            y,
            line,
            10,
            centered=True,
            font_name=_PDF_SECONDARY_FONT,
        )
        y -= 16
    document.setFillColorRGB(0, 0, 0)
    y -= 8
    for section in draft.sections:
        heading_level = _heading_level(section.heading)
        heading_size = 14 if heading_level == 1 else 12
        heading_lines = _wrap(
            section.heading,
            content_width,
            heading_size,
            font_name=(
                _PDF_SECONDARY_FONT
                if heading_level == 2
                else _PDF_HEADING_FONT
            ),
        )
        y = writer.ensure_y(y, minimum=writer.bottom_margin + 44)
        for line in heading_lines:
            _draw_pdf_text(
                document,
                writer.left_margin,
                y,
                line,
                heading_size,
                bold=heading_level != 2,
                font_name=(
                    _PDF_SECONDARY_FONT
                    if heading_level == 2
                    else _PDF_HEADING_FONT
                ),
            )
            y -= 22
        for paragraph in section.paragraphs:
            paragraph_lines = _wrap_first_line(paragraph, content_width, 12, 24)
            y = writer.keep_short_block_together(
                y,
                line_count=len(paragraph_lines),
                line_height=22,
                minimum=writer.bottom_margin + 22,
            )
            for index, line in enumerate(paragraph_lines):
                y = writer.ensure_y(y, minimum=writer.bottom_margin + 22)
                x = writer.left_margin + (24 if index == 0 else 0)
                _draw_pdf_text(document, x, y, line, 12)
                y -= 22
            y -= 2
        document.setFillColor(Color(0.35, 0.35, 0.35))
        for line in _wrap(
            "来源注记：" + "；".join(section.source_refs),
            content_width,
            10,
            font_name=_PDF_SECONDARY_FONT,
        ):
            y = writer.ensure_y(y, minimum=writer.bottom_margin + 18)
            _draw_pdf_text(
                document,
                writer.left_margin,
                y,
                line,
                10,
                font_name=_PDF_SECONDARY_FONT,
            )
            y -= 16
        document.setFillColorRGB(0, 0, 0)
        y -= 8
    writer.finish()
    return _artifact("application/pdf", destination.getvalue())


def validate_approved_draft(draft: ApprovedDraft) -> None:
    """Validate a bounded approved snapshot for controlled downstream workers."""

    _validate_draft(draft)


def _validate_draft(draft: ApprovedDraft) -> None:
    _validate_approval_hash(draft.approval_hash)
    if (
        not draft.title.strip()
        or len(draft.title) > 240
        or _UNSAFE_XML_TEXT_RE.search(draft.title)
    ):
        raise ApprovedDraftBlocked("draft title is invalid")
    if not 1 <= len(draft.sections) <= _MAX_SECTIONS:
        raise ApprovedDraftBlocked("draft section count is invalid")
    paragraphs = 0
    characters = len(draft.title)
    for section in draft.sections:
        if (
            not section.heading.strip()
            or len(section.heading) > 240
            or _UNSAFE_XML_TEXT_RE.search(section.heading)
            or not section.source_refs
        ):
            raise ApprovedDraftBlocked("each section requires a heading and approved source references")
        for source_ref in section.source_refs:
            if (
                not source_ref.strip()
                or len(source_ref) > 240
                or _UNSAFE_XML_TEXT_RE.search(source_ref)
            ):
                raise ApprovedDraftBlocked("draft source reference is invalid")
        for paragraph in section.paragraphs:
            if not paragraph.strip() or _UNSAFE_XML_TEXT_RE.search(paragraph):
                raise ApprovedDraftBlocked("draft paragraph is blank")
            paragraphs += 1
            characters += len(paragraph)
    if paragraphs < 1 or paragraphs > _MAX_PARAGRAPHS or characters > _MAX_TEXT_CHARS:
        raise ApprovedDraftBlocked("draft content exceeds the supported boundary")


def _validate_approval_hash(value: str) -> None:
    if not _SHA256_RE.fullmatch(value):
        raise ApprovedDraftBlocked("draft requires a lawyer approval SHA-256")


def _register_domestic_pdf_fonts() -> None:
    """Register embedded Simplified-Chinese fonts or fail closed.

    Managed Linux runtimes install the three pinned Debian font packages used
    below.  The macOS pair is only a local development-preview equivalent;
    neither path falls back to ReportLab's unembedded built-in CJK font
    references.  Domestic-format release acceptance is performed in the
    managed Linux runtime, where the distinct UKai face is present.
    """

    required_names = {_PDF_TEXT_FONT, _PDF_HEADING_FONT, _PDF_SECONDARY_FONT}
    registered = set(pdfmetrics.getRegisteredFontNames())
    if required_names.issubset(registered):
        return
    with _PDF_FONT_REGISTRATION_LOCK:
        registered = set(pdfmetrics.getRegisteredFontNames())
        if required_names.issubset(registered):
            return
        if (
            _MANAGED_PDF_BODY_FONT.is_file()
            and _MANAGED_PDF_HEADING_FONT.is_file()
            and _MANAGED_PDF_SECONDARY_FONT.is_file()
        ):
            body_path = _MANAGED_PDF_BODY_FONT
            body_index = 0
            heading_path = _MANAGED_PDF_HEADING_FONT
            heading_index = 0
            secondary_path = _MANAGED_PDF_SECONDARY_FONT
            secondary_index = 0
        elif (
            sys.platform == "darwin"
            and _MACOS_PDF_BODY_FONT.is_file()
            and _MACOS_PDF_HEADING_FONT.is_file()
        ):
            body_path = _MACOS_PDF_BODY_FONT
            body_index = 3  # STSongti-SC-Light
            heading_path = _MACOS_PDF_HEADING_FONT
            heading_index = 1  # STHeitiSC-Medium
            # macOS does not expose a stable embeddable Kaiti path.  Keep local
            # development portable with Songti; managed Linux uses UKai above.
            secondary_path = _MACOS_PDF_BODY_FONT
            secondary_index = 3
        else:
            raise ApprovedDraftBlocked(
                "embedded Simplified-Chinese PDF fonts are unavailable"
            )
        try:
            pdfmetrics.registerFont(
                TTFont(_PDF_TEXT_FONT, str(body_path), subfontIndex=body_index)
            )
            pdfmetrics.registerFont(
                TTFont(
                    _PDF_HEADING_FONT,
                    str(heading_path),
                    subfontIndex=heading_index,
                )
            )
            pdfmetrics.registerFont(
                TTFont(
                    _PDF_SECONDARY_FONT,
                    str(secondary_path),
                    subfontIndex=secondary_index,
                )
            )
        except Exception as exc:
            raise ApprovedDraftBlocked(
                "embedded Simplified-Chinese PDF fonts could not be loaded"
            ) from exc


def _heading_level(value: str) -> int:
    """Map only explicit Chinese legal-document numbering to visual levels."""

    prefix = value.lstrip()
    if re.match(r"^（[一二三四五六七八九十百]+）", prefix):
        return 2
    if re.match(r"^\d+(?:\.|、)", prefix):
        return 3
    if re.match(r"^[（(]\d+[）)]", prefix):
        return 4
    return 1


def _configure_domestic_docx(document: Document) -> None:
    """Apply the internal Chinese-lawyer review layout, not a court filing claim."""

    styles = document.styles
    normal = styles["Normal"]
    _set_docx_style_font(normal, _DOCX_BODY_FONT, 12)
    normal.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    normal.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY
    normal.paragraph_format.line_spacing = Pt(22)
    normal.paragraph_format.space_before = Pt(0)
    normal.paragraph_format.space_after = Pt(0)
    normal.paragraph_format.first_line_indent = Pt(24)
    _set_first_line_chars(normal, 200)

    title = styles["Title"]
    _set_docx_style_font(title, _DOCX_TITLE_FONT, 18, bold=True)
    title.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY
    title.paragraph_format.line_spacing = Pt(24)
    title.paragraph_format.space_before = Pt(0)
    title.paragraph_format.space_after = Pt(8)
    title.paragraph_format.first_line_indent = Pt(0)
    title.paragraph_format.keep_with_next = True
    _set_first_line_chars(title, 0)
    _remove_paragraph_borders(title)

    heading_one = styles["Heading 1"]
    _set_docx_style_font(heading_one, _DOCX_HEADING_FONT, 14, bold=True)
    _configure_heading_style(heading_one, before=12, after=4)

    heading_two = styles["Heading 2"]
    _set_docx_style_font(heading_two, _DOCX_SECONDARY_HEADING_FONT, 12)
    _configure_heading_style(heading_two, before=8, after=2)

    heading_three = styles["Heading 3"]
    _set_docx_style_font(heading_three, _DOCX_BODY_FONT, 12, bold=True)
    _configure_heading_style(heading_three, before=6, after=0)

    heading_four = styles["Heading 4"]
    _set_docx_style_font(heading_four, _DOCX_BODY_FONT, 12, bold=True)
    _configure_heading_style(heading_four, before=4, after=0)

    review_note = styles.add_style(_REVIEW_NOTE_STYLE, WD_STYLE_TYPE.PARAGRAPH)
    review_note.base_style = normal
    _set_docx_style_font(review_note, _DOCX_NOTE_FONT, 10)
    review_note.font.color.rgb = RGBColor(0x59, 0x59, 0x59)
    review_note.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
    review_note.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY
    review_note.paragraph_format.line_spacing = Pt(18)
    review_note.paragraph_format.space_before = Pt(0)
    review_note.paragraph_format.space_after = Pt(8)
    review_note.paragraph_format.first_line_indent = Pt(0)
    review_note.paragraph_format.keep_with_next = True
    _set_first_line_chars(review_note, 0)

    source_note = styles.add_style(_SOURCE_NOTE_STYLE, WD_STYLE_TYPE.PARAGRAPH)
    source_note.base_style = normal
    _set_docx_style_font(source_note, _DOCX_NOTE_FONT, 10)
    source_note.font.color.rgb = RGBColor(0x59, 0x59, 0x59)
    source_note.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.LEFT
    source_note.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY
    source_note.paragraph_format.line_spacing = Pt(18)
    source_note.paragraph_format.space_before = Pt(4)
    source_note.paragraph_format.space_after = Pt(8)
    source_note.paragraph_format.first_line_indent = Pt(0)
    _set_first_line_chars(source_note, 0)

    for style_name in ("Header", "Footer"):
        style = styles[style_name]
        _set_docx_style_font(style, _DOCX_BODY_FONT, 9)
        style.font.color.rgb = RGBColor(0x59, 0x59, 0x59)
        style.paragraph_format.first_line_indent = Pt(0)
        style.paragraph_format.space_before = Pt(0)
        style.paragraph_format.space_after = Pt(0)
        _set_first_line_chars(style, 0)

    for section in document.sections:
        section.page_width = Mm(210)
        section.page_height = Mm(297)
        section.top_margin = Mm(30)
        section.bottom_margin = Mm(25)
        section.left_margin = Mm(30)
        section.right_margin = Mm(25)
        section.header_distance = Mm(15)
        section.footer_distance = Mm(17.5)
        section.different_first_page_header_footer = False

        header = section.header
        header.is_linked_to_previous = False
        header_paragraph = header.paragraphs[0]
        header_paragraph.text = "律师复核候选｜待律师终审"
        header_paragraph.style = styles["Header"]
        header_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        footer = section.footer
        footer.is_linked_to_previous = False
        footer_paragraph = footer.paragraphs[0]
        footer_paragraph.text = "非正式文书｜律师复核候选｜第 "
        footer_paragraph.style = styles["Footer"]
        footer_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        _append_page_field(footer_paragraph)
        footer_paragraph.add_run(" 页")

    update_fields = document.settings.element.find(qn("w:updateFields"))
    if update_fields is None:
        update_fields = OxmlElement("w:updateFields")
        document.settings.element.append(update_fields)
    update_fields.set(qn("w:val"), "true")


def _set_docx_style_font(style: object, east_asia_font: str, size: float, *, bold: bool = False) -> None:
    # Keep every run in a CJK-capable family.  python-docx does not emit a
    # per-run East Asian language hint, and headless LibreOffice can therefore
    # classify Chinese glyphs as hAnsi.  If ascii/hAnsi points at Times New
    # Roman those glyphs render as empty squares even though w:eastAsia names a
    # valid Chinese face.  Using the selected legal-document face for all four
    # script slots makes Word and the independent renderer agree while keeping
    # Latin numerals and identifiers readable.
    style.font.name = east_asia_font
    style.font.size = Pt(size)
    style.font.bold = bold
    style.font.italic = False
    style.font.color.rgb = RGBColor(0x00, 0x00, 0x00)
    run_properties = style.element.get_or_add_rPr()
    font_map = run_properties.find(qn("w:rFonts"))
    if font_map is None:
        font_map = OxmlElement("w:rFonts")
        run_properties.insert(0, font_map)
    font_map.set(qn("w:ascii"), east_asia_font)
    font_map.set(qn("w:hAnsi"), east_asia_font)
    font_map.set(qn("w:cs"), east_asia_font)
    font_map.set(qn("w:eastAsia"), east_asia_font)
    font_map.set(qn("w:hint"), "eastAsia")
    for tag in ("w:spacing", "w:kern"):
        inherited = run_properties.find(qn(tag))
        if inherited is not None:
            run_properties.remove(inherited)


def _configure_heading_style(style: object, *, before: float, after: float) -> None:
    paragraph = style.paragraph_format
    paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
    paragraph.line_spacing_rule = WD_LINE_SPACING.EXACTLY
    paragraph.line_spacing = Pt(22)
    paragraph.space_before = Pt(before)
    paragraph.space_after = Pt(after)
    paragraph.first_line_indent = Pt(0)
    paragraph.keep_with_next = True
    paragraph.keep_together = True
    _set_first_line_chars(style, 0)


def _set_first_line_chars(style: object, value: int) -> None:
    paragraph_properties = style.element.get_or_add_pPr()
    indentation = paragraph_properties.find(qn("w:ind"))
    if indentation is None:
        indentation = OxmlElement("w:ind")
        paragraph_properties.append(indentation)
    indentation.set(qn("w:firstLineChars"), str(value))


def _remove_paragraph_borders(style: object) -> None:
    paragraph_properties = style.element.get_or_add_pPr()
    borders = paragraph_properties.find(qn("w:pBdr"))
    if borders is not None:
        paragraph_properties.remove(borders)


def _append_page_field(paragraph: object) -> None:
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instruction = OxmlElement("w:instrText")
    instruction.set(qn("xml:space"), "preserve")
    instruction.text = " PAGE "
    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")
    text = OxmlElement("w:t")
    text.text = "1"
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    paragraph.add_run()._r.append(begin)
    paragraph.add_run()._r.append(instruction)
    paragraph.add_run()._r.append(separate)
    paragraph.add_run()._r.append(text)
    paragraph.add_run()._r.append(end)


def _configure_domestic_workbook_metadata(workbook: Workbook, title: str, approval_hash: str) -> None:
    workbook.iso_dates = True
    workbook.properties.title = title
    workbook.properties.subject = "国内律师付款台账候选（非正式文书）"
    workbook.properties.creator = "律所案件AI工作台"
    workbook.properties.lastModifiedBy = "律所案件AI工作台"
    workbook.properties.category = "律师复核候选"
    workbook.properties.description = _CANDIDATE_STATUS
    workbook.properties.keywords = f"律师复核候选;candidate_sha256:{approval_hash}"
    workbook.properties.created = _OOXML_CORE_DATETIME
    workbook.properties.modified = _OOXML_CORE_DATETIME
    calculation = getattr(workbook, "calculation", None)
    if calculation is not None:
        calculation.calcMode = "manual"
        calculation.fullCalcOnLoad = False
        calculation.forceFullCalc = False


def _register_domestic_xlsx_styles(workbook: Workbook) -> dict[str, str]:
    thin_gray = Side(style="thin", color="7F7F7F")
    light_bottom = Side(style="thin", color="D9D9D9")
    header_border = Border(left=thin_gray, right=thin_gray, top=thin_gray, bottom=thin_gray)
    body_border = Border(bottom=light_bottom)
    source_border = Border(left=thin_gray, bottom=light_bottom)
    styles = {
        "title": NamedStyle(
            name="台账_标题",
            font=Font(name=_XLSX_TITLE_FONT, size=16, bold=True, color="000000", charset=134),
            alignment=Alignment(horizontal="center", vertical="center"),
        ),
        "notice": NamedStyle(
            name="台账_复核提示",
            font=Font(name="楷体", size=10, color="595959", charset=134),
            alignment=Alignment(horizontal="center", vertical="center", wrap_text=True),
        ),
        "header": NamedStyle(
            name="台账_表头",
            font=Font(name=_XLSX_HEADER_FONT, size=11, bold=True, color="000000", charset=134),
            fill=PatternFill(fill_type="solid", fgColor="E7E6E6"),
            border=header_border,
            alignment=Alignment(horizontal="center", vertical="center", wrap_text=True),
        ),
        "text": NamedStyle(
            name="台账_正文文本",
            font=Font(name=_XLSX_BODY_FONT, size=10.5, color="000000", charset=134),
            border=body_border,
            alignment=Alignment(horizontal="left", vertical="center", wrap_text=True),
            number_format="@",
        ),
        "date": NamedStyle(
            name="台账_日期",
            font=Font(name=_XLSX_BODY_FONT, size=10.5, color="000000", charset=134),
            border=body_border,
            alignment=Alignment(horizontal="center", vertical="center"),
            # Keep the stored value typed while using a compact invariant
            # display.  The longer Chinese-literal form can print as ``###``
            # after a wide lawyer ledger is scaled to one landscape A4 page.
            number_format="yyyy-mm-dd",
        ),
        "amount": NamedStyle(
            name="台账_金额",
            font=Font(name=_XLSX_BODY_FONT, size=10.5, color="000000", charset=134),
            border=body_border,
            alignment=Alignment(horizontal="right", vertical="center"),
            number_format='#,##0.00;[Red]-#,##0.00',
        ),
        "amount_text": NamedStyle(
            name="台账_金额原值",
            font=Font(name=_XLSX_BODY_FONT, size=10.5, color="000000", charset=134),
            border=body_border,
            alignment=Alignment(
                horizontal="right", vertical="center", wrap_text=True
            ),
            number_format="@",
        ),
        "integer": NamedStyle(
            name="台账_整数",
            font=Font(name=_XLSX_BODY_FONT, size=10.5, color="000000", charset=134),
            border=body_border,
            alignment=Alignment(horizontal="center", vertical="center"),
            number_format="#,##0",
        ),
        "source": NamedStyle(
            name="台账_来源",
            font=Font(name=_XLSX_BODY_FONT, size=10.5, color="000000", charset=134),
            border=source_border,
            alignment=Alignment(horizontal="left", vertical="center", wrap_text=True),
            number_format="@",
        ),
    }
    for style in styles.values():
        workbook.add_named_style(style)
    return {key: style.name for key, style in styles.items()}


def _configure_domestic_ledger_sheet(
    sheet: object,
    *,
    columns: tuple[str, ...],
    rows: list[
        tuple[str | int | float | Decimal | date | datetime | None, ...]
    ],
    approval_hash: str,
) -> None:
    last_column = get_column_letter(len(columns))
    last_row = len(rows) + 3
    sheet.freeze_panes = "A4"
    sheet.auto_filter.ref = f"A3:{last_column}{last_row}"
    sheet.print_title_rows = "1:3"
    sheet.print_area = f"A1:{last_column}{last_row}"
    sheet.sheet_view.showGridLines = False
    sheet.sheet_view.zoomScale = 90
    sheet.sheet_format.defaultRowHeight = 22
    sheet.row_dimensions[1].height = 30
    sheet.row_dimensions[2].height = 22
    sheet.row_dimensions[3].height = 28
    column_widths: list[float] = []
    for index, column in enumerate(columns, start=1):
        role = _column_role(column)
        widest = max(
            [_display_width(column)]
            + [_display_width(row[index - 1]) for row in rows]
        )
        if role == "date":
            # The underlying value remains a real sortable date.  Reserve
            # enough room for the full ISO display before print scaling.
            width = 15
        elif role == "precision":
            width = 12
        elif role == "amount":
            width = min(max(widest + 1, 12), 13)
        elif role == "currency":
            width = 7
        elif role == "direction":
            width = 11
        elif role == "party":
            width = 14
        elif role == "channel":
            width = 8
        elif role == "reference":
            width = min(max(widest + 1, 12), 16)
        elif role == "nature":
            width = 15
        elif role == "integer":
            width = 8
        elif role == "source":
            width = 18
        else:
            width = min(max(widest + 1, 10), 14)
        column_widths.append(float(width))
        sheet.column_dimensions[get_column_letter(index)].width = width

    for row_index, row in enumerate(rows, start=4):
        wrapped_lines = max(
            _estimated_wrapped_lines(value, width)
            for value, width in zip(row, column_widths, strict=True)
        )
        if wrapped_lines > _MAX_LEDGER_PRINT_LINES_PER_ROW:
            raise ApprovedDraftBlocked(
                "ledger row exceeds the printable wrapped-line boundary"
            )
        sheet.row_dimensions[row_index].height = max(22, wrapped_lines * 15)

    sheet.sheet_properties.pageSetUpPr = PageSetupProperties(fitToPage=True, autoPageBreaks=False)
    sheet.page_setup.orientation = "landscape"
    sheet.page_setup.paperSize = "9"  # ISO A4
    sheet.page_setup.fitToWidth = 1
    sheet.page_setup.fitToHeight = 0
    sheet.page_setup.pageOrder = "overThenDown"
    sheet.page_margins.left = 0.3
    sheet.page_margins.right = 0.3
    sheet.page_margins.top = 0.6
    sheet.page_margins.bottom = 0.6
    sheet.page_margins.header = 0.25
    sheet.page_margins.footer = 0.3
    sheet.oddHeader.center.text = f"{sheet.title}｜律师复核候选"
    sheet.oddHeader.center.font = "黑体,Bold"
    sheet.oddHeader.center.size = 10
    sheet.oddFooter.left.text = "待律师终审｜非正式文书"
    sheet.oddFooter.center.text = "第 &[Page] 页，共 &[Pages] 页"
    sheet.oddFooter.right.text = f"版本摘要 {approval_hash[:12]}"


def _xlsx_cell(sheet: object, value: object, style_name: str) -> WriteOnlyCell:
    cell = WriteOnlyCell(sheet, value=value)
    cell.style = style_name
    return cell


def _xlsx_data_style(styles: dict[str, str], column: str, value: object) -> str:
    role = _column_role(column)
    if role == "date" and isinstance(value, (date, datetime)):
        return styles["date"]
    if role == "amount":
        return styles["amount"] if isinstance(value, (int, float, Decimal)) else styles["amount_text"]
    if role == "integer" and isinstance(value, (int, float, Decimal)):
        return styles["integer"]
    if role == "source":
        return styles["source"]
    return styles["text"]


def _column_role(column: str) -> str:
    normalized = column.strip().casefold()
    if any(token in normalized for token in ("日期精度", "date_precision", "precision")):
        return "precision"
    if any(token in normalized for token in ("日期", "时间", "date", "time")):
        return "date"
    if any(token in normalized for token in ("金额", "本金", "利息", "余额", "合计", "amount", "total")):
        return "amount"
    if any(
        token in normalized
        for token in ("序号", "顺序", "数量", "笔数", "sequence", "count")
    ):
        return "integer"
    if any(token in normalized for token in ("来源", "证据", "source")):
        return "source"
    if any(token in normalized for token in ("币种", "currency")):
        return "currency"
    if any(token in normalized for token in ("方向", "direction")):
        return "direction"
    if any(token in normalized for token in ("付款方", "收款方", "主体", "payer", "payee", "party")):
        return "party"
    if any(token in normalized for token in ("渠道", "channel")):
        return "channel"
    if any(token in normalized for token in ("流水号", "参考号", "reference")):
        return "reference"
    if any(token in normalized for token in ("交易性质", "款项性质", "nature")):
        return "nature"
    return "text"


def _estimated_wrapped_lines(value: object, width: float) -> int:
    if value is None:
        return 1
    rendered = value.isoformat() if isinstance(value, (date, datetime)) else str(value)
    usable_width = max(1, int(width) - 1)
    return max(
        1,
        sum(
            max(1, ceil(_display_width(segment, limit=None) / usable_width))
            for segment in rendered.replace("\r\n", "\n").replace("\r", "\n").split("\n")
        ),
    )


def _display_width(value: object, *, limit: int | None = 80) -> int:
    if value is None:
        return 0
    rendered = value.isoformat() if isinstance(value, (date, datetime)) else str(value)
    width = sum(
        2 if east_asian_width(character) in {"W", "F", "A"} else 1
        for character in rendered
    )
    return min(limit, width) if limit is not None else width


def _safe_cell_value(
    value: str | int | float | Decimal | date | datetime | None,
) -> str | int | float | Decimal | date | datetime | None:
    if value is None:
        return None
    if isinstance(value, bool):
        raise ApprovedDraftBlocked("ledger cell value is invalid")
    if isinstance(value, float):
        if not isfinite(value):
            raise ApprovedDraftBlocked("ledger cell value is invalid")
        return value
    if isinstance(value, Decimal):
        if not value.is_finite():
            raise ApprovedDraftBlocked("ledger cell value is invalid")
        return value
    if isinstance(value, int):
        return value
    if isinstance(value, datetime):
        if value.tzinfo is not None and value.utcoffset() is not None:
            raise ApprovedDraftBlocked("ledger datetime must not contain a timezone")
        return value
    if isinstance(value, date):
        return value
    if not isinstance(value, str) or len(value) > 10_000 or _UNSAFE_XML_TEXT_RE.search(value):
        raise ApprovedDraftBlocked("ledger cell value is invalid")
    candidate = value.lstrip(" \t\r\n")
    return f"'{value}" if candidate.startswith(("=", "+", "-", "@")) else value


class _DomesticPdfWriter:
    def __init__(self, document: canvas.Canvas) -> None:
        self.document = document
        self.left_margin = 30 * mm
        self.right_margin = 25 * mm
        self.top_margin = 30 * mm
        self.bottom_margin = 25 * mm
        self.page_number = 1
        self._draw_header()

    def ensure_y(self, y: float, *, minimum: float) -> float:
        if y >= minimum:
            return y
        return self._start_new_page()

    def keep_short_block_together(
        self,
        y: float,
        *,
        line_count: int,
        line_height: float,
        minimum: float,
    ) -> float:
        """Move a short paragraph intact instead of leaving an orphan line.

        A block longer than a fresh page is still allowed to paginate normally.
        This keeps ordinary legal-analysis paragraphs, dates, and decision
        options from leaving only a closing bracket or punctuation mark at the
        top of the next page.
        """

        if line_count <= 1:
            return y
        fresh_y = A4[1] - self.top_margin
        last_baseline_offset = (line_count - 1) * line_height
        fits_fresh_page = fresh_y - last_baseline_offset >= minimum
        fits_current_page = y - last_baseline_offset >= minimum
        if fits_fresh_page and not fits_current_page:
            return self._start_new_page()
        return y

    def _start_new_page(self) -> float:
        self._draw_footer()
        self.document.showPage()
        self.page_number += 1
        self._draw_header()
        return A4[1] - self.top_margin

    def finish(self) -> None:
        self._draw_footer()
        self.document.save()

    def _draw_header(self) -> None:
        self.document.saveState()
        self.document.setFillColor(Color(0.35, 0.35, 0.35))
        self.document.setFont(_PDF_TEXT_FONT, 9)
        self.document.drawCentredString(A4[0] / 2, A4[1] - 15 * mm, "律师复核候选｜待律师终审")
        self.document.restoreState()

    def _draw_footer(self) -> None:
        self.document.saveState()
        self.document.setFillColor(Color(0.35, 0.35, 0.35))
        self.document.setFont(_PDF_TEXT_FONT, 9)
        self.document.drawCentredString(
            A4[0] / 2,
            17.5 * mm,
            f"非正式文书｜律师复核候选｜第 {self.page_number} 页",
        )
        self.document.restoreState()


def _draw_pdf_text(
    document: canvas.Canvas,
    x: float,
    y: float,
    value: str,
    size: int,
    *,
    centered: bool = False,
    bold: bool = False,
    font_name: str | None = None,
) -> None:
    preferred_font = font_name or (_PDF_HEADING_FONT if bold else _PDF_TEXT_FONT)
    document.saveState()
    if centered:
        x -= _pdf_string_width(value, preferred_font, size) / 2
    text = document.beginText(x, y)
    for font_name, run in _pdf_text_runs(value, preferred_font):
        text.setFont(font_name, size)
        text.textOut(run)
    document.drawText(text)
    document.restoreState()


def _wrap(
    value: str,
    width: float,
    size: int,
    *,
    font_name: str = _PDF_TEXT_FONT,
) -> tuple[str, ...]:
    return _wrap_first_line(value, width, size, 0, font_name=font_name)


def _wrap_first_line(
    value: str,
    width: float,
    size: int,
    first_line_indent: float,
    *,
    font_name: str = _PDF_TEXT_FONT,
) -> tuple[str, ...]:
    lines: list[str] = []
    current = ""
    first_output_line = True
    normalized = value.replace("\t", "    ").replace("\r\n", "\n").replace("\r", "\n")
    for unit in _pdf_wrap_units(normalized):
        if unit == "\n":
            lines.append(current.rstrip())
            current = ""
            first_output_line = False
            continue
        available_width = width - (first_line_indent if first_output_line and not lines else 0)
        if not current and unit.isspace():
            continue
        candidate = current + unit
        if _pdf_string_width(candidate, font_name, size) <= available_width:
            current = candidate
            continue

        # Closing punctuation belongs to the preceding Chinese clause.  A
        # one-glyph optical overhang is preferable to starting a page or line
        # with a detached bracket or full stop.
        if current and unit in "，。；：！？、）》】〕〉」』）]};:,.!?%":
            current += unit
            continue

        carry = ""
        if current and current[-1] in "（《【〔〈「『([{" :
            carry = current[-1]
            current = current[:-1]
        if current.rstrip():
            lines.append(current.rstrip())
            first_output_line = False
        current = carry

        if unit.isspace():
            continue
        available_width = width
        candidate = current + unit
        if _pdf_string_width(candidate, font_name, size) <= available_width:
            current = candidate
            continue

        # Exceptionally long machine identifiers and official-source URLs may
        # exceed a whole legal-document line.  Split only those oversized
        # units; ordinary dates, amounts, scenario IDs and authority IDs stay
        # intact.
        oversized = candidate
        current = ""
        while oversized:
            prefix = ""
            split_at = 0
            for index, char in enumerate(oversized, start=1):
                if prefix and _pdf_string_width(
                    prefix + char, font_name, size
                ) > available_width:
                    break
                prefix += char
                split_at = index
            if not prefix:
                prefix = oversized[0]
                split_at = 1
            oversized = oversized[split_at:]
            if oversized:
                lines.append(prefix)
                first_output_line = False
            else:
                current = prefix
    if current or not lines:
        lines.append(current.rstrip())
    return tuple(lines)


def _pdf_wrap_units(value: str) -> tuple[str, ...]:
    """Tokenize only machine-like text; Chinese prose remains breakable.

    Character-by-character wrapping made dates, amounts, IDs and L1/L2 labels
    appear as different facts across two lines.  Treat contiguous ASCII
    machine tokens and RMB amounts as one unit while preserving normal Chinese
    line breaking.
    """

    units: list[str] = []
    index = 0
    machine_characters = frozenset("._:/%_-#?&=+@")
    while index < len(value):
        char = value[index]
        if char == "\n":
            units.append(char)
            index += 1
            continue
        if char.isspace():
            end = index + 1
            while end < len(value) and value[end].isspace() and value[end] != "\n":
                end += 1
            units.append(value[index:end])
            index = end
            continue
        if char == "￥" and index + 1 < len(value) and value[index + 1].isdigit():
            end = index + 2
            while end < len(value) and (
                value[end].isdigit() or value[end] in ",.%"
            ):
                end += 1
            units.append(value[index:end])
            index = end
            continue
        if char.isascii() and (char.isalnum() or char in "#@"):
            end = index + 1
            while end < len(value):
                candidate = value[end]
                if not candidate.isascii() or not (
                    candidate.isalnum() or candidate in machine_characters
                ):
                    break
                end += 1
            units.append(value[index:end])
            index = end
            continue
        units.append(char)
        index += 1
    return tuple(units)


def _pdf_string_width(value: str, preferred_font: str, size: int) -> float:
    return sum(
        pdfmetrics.stringWidth(run, font_name, size)
        for font_name, run in _pdf_text_runs(value, preferred_font)
    )


def _pdf_text_runs(value: str, preferred_font: str) -> tuple[tuple[str, str], ...]:
    candidate_fonts = (preferred_font,) + tuple(
        font_name
        for font_name in (
            _PDF_TEXT_FONT,
            _PDF_HEADING_FONT,
            _PDF_SECONDARY_FONT,
        )
        if font_name != preferred_font
    )
    runs: list[tuple[str, str]] = []
    current_font = ""
    current_text = ""
    for character in value:
        codepoint = ord(character)
        unicode_category = category(character)
        # ReportLab 4.x writes an invalid one-code-unit ToUnicode mapping for
        # astral characters even when a managed font contains the glyph.  It
        # also draws several combining/format controls as visible boxes or
        # separate glyphs.  Legal names and quoted source text must never be
        # silently changed, detached or made unsearchable, so the direct-PDF
        # fallback rejects these inputs.  The Office-rendered DOCX/PDF path is
        # the governed route for text that needs shaping or astral coverage.
        if (
            codepoint > 0xFFFF
            or codepoint in {0xFFFC, 0xFFFD}
            or unicode_category.startswith("M")
            or unicode_category in {"Cc", "Cf", "Cs", "Co", "Cn"}
        ):
            raise ApprovedDraftBlocked(
                "embedded PDF renderer cannot safely preserve "
                f"U+{codepoint:04X} (Unicode category {unicode_category})"
            )
        font_name = next(
            (
                candidate
                for candidate in candidate_fonts
                if _pdf_font_has_visible_glyph(candidate, character)
            ),
            None,
        )
        if font_name is None:
            raise ApprovedDraftBlocked(
                f"embedded PDF fonts cannot render U+{codepoint:04X}"
            )
        if font_name == current_font:
            current_text += character
            continue
        if current_text:
            runs.append((current_font, current_text))
        current_font = font_name
        current_text = character
    if current_text:
        runs.append((current_font, current_text))
    return tuple(runs)


def _pdf_font_has_visible_glyph(font_name: str, character: str) -> bool:
    """Reject cmap entries whose TrueType glyph has no drawable outline.

    Some managed CJK fonts advertise a character in their cmap/advance table
    but leave its glyph data empty.  ReportLab then advances one full cell and
    silently prints a blank.  Ordinary Unicode spaces are the only intentional
    empty glyphs accepted here; every other character must have real glyph
    data so the caller can fall through to the next managed font.
    """

    codepoint = ord(character)
    face = pdfmetrics.getFont(font_name).face
    if codepoint not in face.charWidths:
        return False
    glyph_index = face.charToGlyph.get(codepoint)
    if glyph_index is None:
        return False
    if category(character) == "Zs":
        return True
    glyph_positions = face.glyphPos
    return (
        glyph_index >= 0
        and glyph_index + 1 < len(glyph_positions)
        and glyph_positions[glyph_index + 1] > glyph_positions[glyph_index]
    )


def _deterministic_ooxml(content: bytes, *, docx_fonts: tuple[str, ...] = ()) -> bytes:
    """Repack Office ZIPs with stable member order/timestamps for audit hashes."""

    source = BytesIO(content)
    destination = BytesIO()
    with ZipFile(source, "r") as archive, ZipFile(
        destination,
        "w",
        compression=ZIP_DEFLATED,
        compresslevel=9,
    ) as output:
        for name in sorted(archive.namelist()):
            item = ZipInfo(name, date_time=_OOXML_TIMESTAMP)
            item.compress_type = ZIP_DEFLATED
            item.create_system = 0
            item.external_attr = 0
            item.extra = b""
            item.comment = b""
            member = archive.read(name)
            if name == "word/fontTable.xml" and docx_fonts:
                member = _augment_docx_font_table(member, docx_fonts)
            if name == "docProps/core.xml":
                member = _normalize_ooxml_core_properties(member)
            output.writestr(item, member, compress_type=ZIP_DEFLATED, compresslevel=9)
    return destination.getvalue()


def _normalize_ooxml_core_properties(content: bytes) -> bytes:
    """Remove library save-time drift from otherwise identical Office files."""

    normalized = content
    for field in (b"created", b"modified"):
        pattern = re.compile(
            rb"(<dcterms:"
            + field
            + rb"\b[^>]*>)[^<]*(</dcterms:"
            + field
            + rb">)"
        )
        normalized, count = pattern.subn(
            rb"\g<1>" + _OOXML_CORE_DATETIME_TEXT + rb"\g<2>",
            normalized,
            count=1,
        )
        if count != 1:
            raise ApprovedDraftBlocked(
                "Office core properties lack a deterministic timestamp"
            )
    return normalized


def _augment_docx_font_table(content: bytes, fonts: tuple[str, ...]) -> bytes:
    """Declare every portable CJK face and its macOS alternative.

    python-docx writes style references but omits non-template faces from
    ``fontTable.xml``.  LibreOffice then treats the missing east-Asian family
    as unavailable and emits empty-square glyphs even when the font is
    installed.  Explicit declarations plus ``w:altName`` make the editable
    DOCX portable without embedding or redistributing proprietary font files.
    Managed Linux still resolves the primary domestic names through the
    audited fontconfig alias file.
    """

    closing = b"</w:fonts>"
    if closing not in content:
        raise ApprovedDraftBlocked("DOCX font table is malformed")
    entries: list[str] = []
    for font in dict.fromkeys(fonts):
        encoded_name = f'w:name="{xml_escape(font, quote=True)}"'.encode("utf-8")
        if encoded_name in content:
            continue
        family = "swiss" if font in {_DOCX_TITLE_FONT, _DOCX_HEADING_FONT} else "roman"
        alternate = _DOCX_FONT_ALTERNATES.get(font)
        alternate_xml = (
            f'<w:altName w:val="{xml_escape(alternate, quote=True)}"/>'
            if alternate is not None
            else ""
        )
        entries.append(
            f'<w:font w:name="{xml_escape(font, quote=True)}">'
            + alternate_xml
            + '<w:charset w:val="86"/>'
            + f'<w:family w:val="{family}"/>'
            + '<w:pitch w:val="variable"/>'
            + '</w:font>'
        )
    if not entries:
        return content
    return content.replace(closing, "".join(entries).encode("utf-8") + closing, 1)


def _artifact(media_type: str, content: bytes) -> DraftArtifact:
    if not content:
        raise ApprovedDraftBlocked("draft generator returned an empty artifact")
    return DraftArtifact(media_type, content, sha256(content).hexdigest())
